# Generated by Django 4.0.5 on 2022-07-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AddField(
            model_name='course',
            name='idx',
            field=models.IntegerField(default=0),
        ),
    ]
